Huge polishing update
hh-school/bot-resume-builder pull request #13
Opened 2017-03-31 19:11 UTC by Trympyrym

В этом апдейте:

- Постарался сделать то же, что и в rearrange PR-е
- Рефактор того самого куска в telegramAdapter
- Тело бота сильно переработано:
-- Внесены некоторые правки из версий, показанных на демо
-- Теперь бот может в ответ на одно сообщение пользователя генерировать несколько сообщений подряд
-- Добавлена возможность выдавать резюме в разных форматах. (Пока добавил только PLAIN_TEXT, который был на демо показан)
-- Id сервисных текстов переделан на перечисление.

2017-04-01 16:31 UTC, khasanovbi requested changes

2017-04-01 16:31 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +        Queue<QuestionGenerator> questionGenerator = messageHandler.handle(answer);
questionGenerator -> questionGeneratorQueue

2017-04-01 16:31 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/TextsStorage.java
> +        ALREADY_STARTED, UNKNOWN, OOPS_TRY_RESTART, HELLO, CLEARED, FINISHED, EMPTY;
1. Думаю стоит вынести в отдельный файл 
2. Может стоит в enum держать какое-то уникальное стринговое поле типа `type`. Чтобы потом можно было это из файла или из базы поставить в соответствие тип вопроса.

2017-04-01 16:31 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/TextsStorage.java
> +}
Новая строка на конце

2017-04-01 16:31 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
опять же может в новый файл?

2017-04-01 16:31 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/answer/TelegramAnswerFactory.java
> +    public static boolean canHandleUpdate(Update update) {
Кажется эти методы не связаны с фабрикой

2017-04-01 16:31 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/answer/ProtoTelegramAnswer.java
> +public abstract class ProtoTelegramAnswer implements TelegramAnswer {
Может стоит перенести методы TelegramAnswer в ProtoTelegramAnswer, кажется хватит одного слоя абстракции.

2017-04-01 16:56 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/answer/ProtoTelegramAnswer.java
> +public abstract class ProtoTelegramAnswer implements TelegramAnswer {
перенес

2017-04-01 16:57 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/TextsStorage.java
> +        ALREADY_STARTED, UNKNOWN, OOPS_TRY_RESTART, HELLO, CLEARED, FINISHED, EMPTY;
Перечисление в отдельный файл вынес, пункт 2 не понял. Этот кусок не про вопросы, это хранилище фиксированных текстов.

2017-04-01 17:01 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
нутром чую, что литр...

В общем, это как Map.Entry. Не имеет никакого смысла без родительского класса и используется только для обхода answers в UserData. Считаю, что не стоит в отдельный файл выносить.

2017-04-01 17:44 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextId.java
> +    ALREADY_STARTED, UNKNOWN, OOPS_TRY_RESTART, HELLO, CLEARED, FINISHED, EMPTY;
`;` лишняя вроде бы.

2017-04-01 17:54 UTC, khasanovbi approved these changes

2017-04-02 21:58 UTC, asundukov reviewed
очень сложно читать сотни строк абстрактного апйдета без конкретной задачи - если есть пулл-реквест и нет описания задачи - то надо хотя бы в общих чертах написать в чем цель, что сделано и для чего. Всё это приходится додумывать в процессе чтения кода и это большая боль.

UPD - сорри, не заметил сразу описание к PR.

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +                resultBuilder.append(entry.getQuestion());
как идея: вместо getQuestion() сделать еще getCaption и нормально не виде вопрос-ответ этот формат, а виде резюме в PLAIN_TEXT.

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +public enum CVFormats {
че то мне не нравится использование логики внутри enum-типа. Как-то алогично кажется. Я конечно могу ошибаться но может быть лучше как-то скомбинировать в виде классов с интерфейсом?

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +        public String build(ChatId chatId) {
по самой структуре метода - более чистым код будет выглядеть если вынести внутренности цикла в отдельный метод, а еще каждый набор аппендов для вопроса и для ответа тоже в отдельные методы.

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +import ru.hh.resumebuilderbot.telegram.adapter.TelegramAdapter;
с учетом того что в файле ничего кроме этого не поменялось - выглядит как unusage import.

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +import java.util.*;
=\

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +        return instance.questionTexts.get(questionId);
зачем нам вообще хранить instance в статичном полеи ползать в его не статичные поля, если можно просто поля класса статичными сделать?

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +        registerQuestion(text, null);
почему бы вместо этой строки не вписать instance.questionTexts.add(text); 
а в функции убрать проверку на null и сделать код без веток ?

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
Да, вложенный класс с "универсальным названием" и вправду вводит в заблуждение.
Насколько я вижу тут смысл в том что это запись одного ответа пользователя на один вопрос и эта комбинация вполе реюзабельная в других частях проекта и ее действительно можно вынести.
Вопросов у нас вполне себе ограниченное количество  и в бд они будут храниться по айдишнику - под них вообще имхо стоило бы завести отдельный класс.

2017-04-02 21:58 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/TelegramAdapter.java
> +import ru.hh.resumebuilderbot.*;
=\

2017-04-02 22:01 UTC, asundukov commented
по дублированию ты спрашивал - я не понял куда смотреть, лучше тоже самому комментить те места в которых сомневаешься чтоб ревьюеры на них обратили внимание. Когда код не пишешь а только ревьюишь - совершенно на другие штуки внимание обращаешь и не понимаешь какие были боли у автора кода.

2017-04-02 22:04 UTC, asundukov commented
Я бы вынес очередь ответов в отдельный класс. реализацию очереди лучше скрыть от других классов, потенциально может появиться еще какая-то логика там, например логгинг какой-то, паузы, дополнение какими данными и т.д.

2017-04-02 22:12 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +    private Map<Integer, List<String>> allowedAnswers = Collections.synchronizedMap(new HashMap<>());
synchronized-реалзации вводят в заблуждение потому что кажется что они используются т.к. возможна конкуретная запись или запись/чтение в них. Но этого нет, у нас однопоточная запись только при создании. можно заиспользовать Collections.unmodifiableList .

2017-04-02 22:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +        registerQuestion(text, null);
как сказал один хороший человек - "NPE-непробиваемый код это может быть и хорошо, но потом за всей этой непробиваемостью не будет видно самой логики" :) так что чем раньше и чем ближе к проблеме код будет падать с NPE - тем четче и прогнозируемее он будет работать в перспективе после фиксов (да и сам поиск багов будет быстрее).

2017-04-03 06:19 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
Подумал еще раз, вынес в отдельный класс. Заодно package сделал отдельный.

"под них вообще имхо стоило бы завести отдельный класс." - под вопросы? есть уже отдельный класс вроде

2017-04-03 06:32 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +public enum CVFormats {
Немного переделал. Но во избежание enum-switch антипаттерна оставил в enum-е метод getBuilder().

2017-04-03 06:36 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +        public String build(ChatId chatId) {
Починил

2017-04-03 07:05 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +        return instance.questionTexts.get(questionId);
Починил

2017-04-03 07:13 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +import ru.hh.resumebuilderbot.telegram.adapter.TelegramAdapter;
файл TelegramAdapter был перенесен. отсюда изменение строк с импортом

2017-04-03 07:15 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +                resultBuilder.append(entry.getQuestion());
Этот класс создан для маппинга в БД. Он данные хранить должен. И иногда отдавать. Но форматировать резюме - это совсем не его задача.

2017-04-03 07:18 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
а почему тогда в Entry используется String а не Question или questionId?

2017-04-03 07:32 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/UserData.java
> +    public class Entry {
Потому, что в Question присутствует ChatID. Этот косячок делает его (класс Question) не очень юзабельным для хранения вопросов в БД. А делать такой же класс, но без ChatId тоже было бы косячно. Это исправлено в ветке, где я делаю алгоритмо-подобную структуру вопросов. Так что для этого PR предлагаю так оставить.

2017-04-03 07:34 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/CVFormats.java
> +                resultBuilder.append(entry.getQuestion());
да, тогда уже более ок. если хранить данные и иногда отдавать это в виде строки для "сервисных задач" - то тогда может toString заиспользовать?

2017-04-03 08:19 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +    private Map<Integer, List<String>> allowedAnswers = Collections.synchronizedMap(new HashMap<>());
Просто заменить synchronized на unmodifiable не получится, ибо нужно будет менять начальное заполнение этого списка. Т.к. обе этих коллекции будут сильно переделаны в параллельной ветке, для этого PR предлагаю так оставить.

2017-04-03 08:33 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +        questionGeneratorQueue.forEach((x) -> messengerAdapter.ask(x.generateNext(answer.getChatId())));
x.generateNext может вызываться внутри QuestionGeneratorsQueue .
получается сейчас мы в этой функции получаем доступ к внутренностям самой очереди.

пока мне кажется что правильнее убрать forEach и вызывать какой-то новый метод с другим имененем и передавать туда adapter и chatId (или answer). А может бы и в messengerAdapter передавать questionGeneratorQueue и chatId(или answer) чтоб он сам пробегался по очереди. 

Короче мне тут лямбда не нравится т.к. мне кажется что можно очевиднее код сделать с прямой передачей параметров вместо хитрой передачи в виде консьюмеров.

2017-04-03 08:50 UTC, asundukov approved these changes
да, поинтереснее становится :)

2017-04-03 11:44 UTC, merged