WIP - Db
hh-school/bot-resume-builder pull request #15
Opened 2017-04-09 11:56 UTC by KhasanovBI

2017-04-09 12:09 UTC, asundukov commented on src/main/resources/hibernate.properties
> +hibernate.connection.password=ashjdfh1j23lkdas
опять хардкод паролей

2017-04-09 12:15 UTC, KhasanovBI commented on src/main/resources/hibernate.properties
> +hibernate.connection.password=ashjdfh1j23lkdas
Это после задачи с докером исправлю.

2017-04-15 11:33 UTC, Trympyrym requested changes
По результатам встречи последней:
* Образование пишем в одну таблицу
* Мне нужно для каждого юзера хранить номер текущей ноды
* Для записи графа в БД мне в будущем понадобится табличка 'Граф' со следующими колонками: node id (primary key, НЕ автоинкремент), serialized node class (строка)
* К теме циклов возвращаясь: для образования и места работы нужно хранить айдишку текущей заполняемой строки. Хранить предлагаю в одной табличке с индексом текущей ноды.

2017-04-16 20:32 UTC, Trympyrym requested changes

2017-04-16 20:32 UTC, Trympyrym commented on sql/create.sql
> +  id        SERIAL PRIMARY KEY,
ID ноды берется из XML-ки с вопросами. Это не SERIAL.

2017-04-16 20:32 UTC, Trympyrym commented on sql/create.sql
> +);
кроме classpath нужна еще колонка с самой нодой (сериализованной)

2017-04-16 20:32 UTC, Trympyrym commented on sql/create.sql
> +);
new line

2017-04-16 20:32 UTC, Trympyrym commented on sql/create.sql
> +  node_id          INT,
Вот этого куска совсем не понял. Почему нода сейчас не референсит node (id) ? Что за node_relation_id ?

2017-04-17 07:25 UTC, Trympyrym approved these changes

2017-04-17 08:09 UTC, savinsergey commented on sql/create.sql
> +  "end"        DATE,
Зачем "end" в кавычках?

2017-04-17 08:10 UTC, KhasanovBI commented on sql/create.sql
> +  "end"        DATE,
служебное слово

2017-04-17 08:12 UTC, asundukov commented on sql/create.sql
> +  "end"        DATE,
почему мы служебные слова используем в названиях  полей таблиц? потом же куча геморра запросы писать.

почему не сделать start_date и end_date?

2017-04-17 08:16 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/database/dao/education/EducationDAOImpl.java
> +        implements EducationDAO {
почему new line?

2017-04-17 08:17 UTC, khasanovbi commented on sql/create.sql
> +  "end"        DATE,
Ок, но `user`а так и оставлю. Я понимаю, что кто-то может накосячить с этим, но это не критично.

2017-04-17 08:25 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/dao/education/EducationDAOImpl.java
> +        implements EducationDAO {
Убрал, просто до этого тут был другой класс с длинным названием.

2017-04-17 09:06 UTC, merged