added root attribute to XML file
hh-school/bot-resume-builder pull request #20
Opened 2017-04-12 14:41 UTC by Trympyrym

* Теперь нода-рут задается явно в XML файле
* Проверка структуры графа вопросов теперь происходит один раз при чтении из XML (была при сборке для каждого пользователя)
* Небольшие улучшения кода классов NodeSet и XMLParser
* Исправлена ошибка - QuestionsStorage.getRoot() выдавал неверный рут
* Исправлена ошибка - при клонировании NodeSet не устанавливался рут

2017-04-12 16:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSet.java
> +    NodeSet(List<XMLParser.Entry> rawData) throws IOException {
Я бы сделал метод public static NodeSet fromXML(List<XMLParser.Entry> rawData), как-то не очень ожидаешь при создании объекта получить ошибку, но это так дело вкуса.

2017-04-12 16:49 UTC, khasanovbi approved these changes

2017-04-13 08:49 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSet.java
> +    NodeSet(List<XMLParser.Entry> rawData) throws IOException {
Идея понятна. В следующем PR сделаю более понятно это дело.

2017-04-13 09:05 UTC, asundukov requested changes

2017-04-13 09:05 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSet.java
> +            throw new IOException("Error parsing XML");
как потом разбирать почему упало? нужно будет посмотреть еррор, потом залезть в эту функцию, потом залезть в isValid. А там несколько причин почему возвращается false. Потом опять лезть в XML и проверять каждую причину.

Как лучше:
- boolean isValid превращаем в void checkValid throws IOException.
- отсюда вызываем checkValid без всяких условий и прокидываем выше этот эксепшн.
- в checkValid, в нужных местах разумеется, - ошибки с более говорящими текстами

еще - прокидывание ошибок с самого низа до самого верха не всегда прикольно смотрится, иногда интереснее кинуть рантайм еррор или любой расширенный еррор отнаследованный от рантайма. Ловить можно в нужном месте но явно везде не прокидывать. Но тут уже дело вкуса. Холивары бывают :) я лично не люблю throwns по всему коду и предпочитаю использовать рантайм еррор там где обычно все ок должно работать.

2017-04-13 09:05 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSet.java
>      private class Entry {
класс NodeSet прилично разросся, имхо its time to use class extract. Ну короче имхо пора вынести и валидацию в отдельный класс и Entry.

2017-04-13 09:05 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/XMLParser.java
>      List<Entry> parse(String filename) {
вот этот метод пора побить на меншие методы.

как минимум все что внутри try вынести в метод, и внутренности каждого for вынести в метод.

У каждого метода должен быть только один уровень абстракции. Когда в голове нужно держать несколько слоев логики - читать становится совсем нереально. Ну и разумеется каждый заголовок метода дает коммантарий что вообще происходит в 2 словах.

2017-04-13 11:42 UTC, asundukov approved these changes
весь makeEntry выглядит так, будто лучше вынести эту логику в фабрику для XMLEntry. XMLEntry расширить на каждый тип, а фабрика будет отдавать верное расширение XMLEntry. 
makeEntry будет вызывать метод в расширенном XMLEntry где будет зашита логика создания нужного NodeSetEntry.
Тогда уйдет и проблема с дублированием isRoot(), а сам метод будет намного короче и без повторяющихся IF'ов.

Вообще длинные похожие IF'ы - явный признак того что сделав правильные объекты на основе одного интерфейса можно все IF'ы с помощью фабрики заменить на короткий switch-case, а нижнего уровня спрятать ниже. Часто она не важна на этом уровне.

Ну в общем тут аппрувлю, тут возможно будет некий овер-инжиниринг уже. По пониманию как работает код "в целом" может быть будет немного сложнее, а вот для мелких будущих правок - намного проще (когда мы просто по Ctrl+Click) переходим к нужному коду в методах по 1-10 строк.

2017-04-13 11:42 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSetEntry.java
> +    private NodeSetEntry(QuestionNode node, int nextIndex, int nextIndexYes, int nextIndexNo) {
настолько перегруженный однотипными данными конструктор - плохо. Удалил последний индекс от вызова этого конструктора где-то - сразу получил совсем иное поведение без всяких эксепшенов.
Ну и сам вызов конструктора с 3 параметрами и более, тем более числовыми - будет выглядеть магией. Лучше тогда оставить сеттере и явно сеттить переменные где это требуется.

2017-04-13 11:44 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSetEntry.java
> +    private NodeSetEntry(QuestionNode node, int nextIndex, int nextIndexYes, int nextIndexNo) {
хотя он тут приватный и возможно это норм, но два конструктора еще остались публичные с похожими по типам параметрами, в общем тут наверное ок, но на грани :)

2017-04-13 11:48 UTC, merged