36 skip command
hh-school/bot-resume-builder pull request #23
Opened 2017-04-14 16:15 UTC by Trympyrym

* Команда /skip
    * Добавлена в селектор
    * Добавлен соответствующий handler
    * Добавлено значение TextId и соответствующий ему текст в TextsStorage для случая, когда вопрос пропустить нельзя
    * Добавлена функция skippable() в интерфейс QuestionNode
    * Добавлен тэг skippable в XML файл
* Удалена циклонода
* Изменена структура XML файла (часть атрибутов вынесена в список <classData> внутри <graphNode>)
* Еще немного рефактора XML парсера.

2017-04-16 18:36 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/QuestionsLoader.java
> +        return NodeSet.fromXMLFile(filename);
А нужен ли этот класс теперь?

2017-04-16 19:30 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextsStorage.java
> +        textsMap.put(TextId.CANT_SKIP,
Не в этом PR, предложение на будущее, привязать каждый текст в enum

2017-04-16 19:35 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserData.java
> +        return currentState.currentNodeIsSkippable();
В каждом методе используется currentState, такое ощущение, что стоит объединить UserData и UserState в один.

2017-04-16 19:39 UTC, khasanovbi requested changes

2017-04-16 19:39 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/NodeSetEntry.java
> +        if (xmlEntry.getType().equals("terminal")) {
Может стоит разбить их на несколько, отдельных методов для создания разных типов, чтобы потом было легче сделать один унифицированный, мы же к этому идем насколько я понял.

2017-04-16 20:34 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/QuestionsLoader.java
> +        return NodeSet.fromXMLFile(filename);
NodeSet или QuestionsLoader?

2017-04-16 20:48 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/QuestionsLoader.java
> +        return NodeSet.fromXMLFile(filename);
QuestionsLoader

2017-04-16 21:03 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextsStorage.java
> +        textsMap.put(TextId.CANT_SKIP,
С сеттерами и геттерами? Жирно слишком для енума

2017-04-16 21:06 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserData.java
> +        return currentState.currentNodeIsSkippable();
Это позже, я тебе об этом писал. Когда с БД код дружить будем.

2017-04-16 21:07 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/QuestionsLoader.java
> +        return NodeSet.fromXMLFile(filename);
По ходу не особо. Утром еще раз гляну.

2017-04-16 21:13 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserData.java
> +        return currentState.currentNodeIsSkippable();
И правда

2017-04-16 21:21 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextsStorage.java
> +        textsMap.put(TextId.CANT_SKIP,
setter'ы не нужны же. Насчет жирности это как посмотреть, я вот вижу в enum синтаксический сахар классов и конечного числа объектов, и если есть функциональность, почему бы не заюзать. Маппить один к одному в другом классе вроде тоже не очень. Возможно, я бы даже эту textsMap сложил бы в enum static'ом и все было бы в одном месте, но это опять же имхо.

2017-04-17 06:31 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextsStorage.java
> +        textsMap.put(TextId.CANT_SKIP,
setter-ы не нужны, но нужен loader.

Сейчас я вижу 2 разные сущности: перечисление - TextId - идентификатор для загрузки этого текста из файла и для использования его в коде. И TextsStorage, который есть хранилище и имеет свои, хранилищные методы (которых пока нет, но тот же loader будет обязательно). Точнее объяснить не могу, но имхо склеивать их неправильно. Если не убедил, то можно вынести этот вопрос на вторник.

2017-04-17 07:11 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/QuestionsStorage.java
> +    private static final String XMLfilename = "src/main/resources/questions.xml";
`xmlFilename`

2017-04-17 07:14 UTC, KhasanovBI commented on .gitignore
> +log.log
new line

2017-04-17 07:16 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/texts/storage/TextsStorage.java
> +        textsMap.put(TextId.CANT_SKIP,
Не совсем понимаю что ты подразумеваешь под loader, расскажи в личке плс. Как я и писал не в этом PR, это просто на будущее.

2017-04-17 07:17 UTC, khasanovbi approved these changes

2017-04-17 08:02 UTC, asundukov requested changes
критичное:
отписал в паре мест

некритичное:
прокидывание boolean skippable везде по методам - ад, еще несколько подобных параметров и за сигнатурами и вызовами этих методов вообще кода не будет видно)

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/CurrentUserState.java
> +    }
по названию класса - чем _Current_ UserState отличается от какого-то еще абстрактного UserState ? мне кажется слово "current" - больше подходит примениме к переменной, чем к классу.

и по смысле и current для QuestionNode здесь не нужно, UserState же уже current.

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/QuestionsStorage.java
> +import static ru.hh.resumebuilderbot.question.storage.builder.Graph.fromXMLFile;
просто вопрос. Есть какая-то причина в static imort? ну т.е. оно само так получилось или умышленно ради упрощения кода?
а то у меня самого не сформировалось еще мнение в том стоит ли именно так делать или напрямую вызывать.

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/Graph.java
> +    private void linkNodes() {
грусть

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/Graph.java
> +    private void linkNodes() {
что если передавать nodesMap внутрь entry чтоб оно само конфигурило своим ноды? т.е. делегировать им эту работу - они же уже разных классов, зачем это здесь проверять если оно уже "зашито" в их определении класса? ну типа метод linkNodes(Map<Integer, GraphEntry> nodesMap). Ну и если будешь делать то еще можно подумать может быть всю структуру Map<Integer, GraphEntry> nodesMap стоит скрыть под NodesMap, чтоб не таскать такую структуру по коду.

не могу понять лучше ли будет, но двух похожих if'ов с instanceof точно не будет.

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/xml/parser/XMLEntry.java
>      static XMLEntry fromGraphNode(Node graphNode) throws IOException {
1. слишком длинный метод
1. уже вроде писал - если сделать для XMLEntry фабрику и передавать туда type чтоб оно возвращало нужный тип XMLEntry то сразу куча кода упростилась бы тут и в GraphEntry. В фабрику можно передавать целиком ноду, эту ноду она будет передавать в конструктор конкретной XMLEntry и ентря сама будет заниматься своим созданием.

Не к текущему PR, но я каждый раз буду это писать пока буду видеть непонятный код в методах в 10+ строк :)
А каждый следующий PR без этих изменений будет сложнее и сложнее. Тех.долг в действии, даже тех.кредит :smile:

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/GraphEntry.java
> +            return makeTerminalEntry(xmlEntry, classData);
зачем увеличиать сложность сигнатур методов если classData это уже часть xmlEntry и передается внутри него?

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/xml/parser/XMLEntry.java
> +                .forEach((x) -> result.put(x.getNodeName(), x.getTextContent()));
у x тут скобочки вроде можно убрать .
```
 .forEach(x -> result.put(x.getNodeName(), x.getTextContent()));
```

2017-04-17 08:02 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/xml/parser/XMLNodeListStream.java
> +                .filter((x) -> x.getNodeName().equals(name))
и тут скобочки

2017-04-17 08:13 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/QuestionsStorage.java
> +import static ru.hh.resumebuilderbot.question.storage.builder.Graph.fromXMLFile;
Идея сама так

2017-04-17 08:15 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/xml/parser/XMLNodeListStream.java
> +                .filter((x) -> x.getNodeName().equals(name))
Что со скобками не так? Это не дублирование, это типа ( () () () ).

2017-04-17 08:18 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/GraphEntry.java
> +            return makeTerminalEntry(xmlEntry, classData);
Когда переделаю линки, в эти методы будет передаваться classpath, links и classData. XMLEntry туда передаваться не будет.

2017-04-17 08:18 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/xml/parser/XMLNodeListStream.java
> +                .filter((x) -> x.getNodeName().equals(name))
понял

2017-04-17 08:39 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/builder/Graph.java
> +    private void linkNodes() {
linkNodes - переделаю.
nodesMap - приватное поле Graph. За пределы Graph выносить его не хочу.

2017-04-17 09:08 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/CurrentUserState.java
> +    }
Это будет схлопнуто с следующем PR, когда код с БД сводить будем.

2017-04-17 09:08 UTC, asundukov approved these changes

2017-04-17 09:16 UTC, merged