Юнит-тесты для загрузчика XML
hh-school/bot-resume-builder pull request #25
Opened 2017-04-19 09:03 UTC by Trympyrym

* Добавлены юнит-тесты на загрузчик XML
* Удален класс CurrentUserState
* Новый формат хранения связей в графе
    * В файле XML
    * В классе XMLEntry
    * В классе GraphEntry
* Удалена реализация PlainTextCVBuilder
* Изменена структура пакетов в question.storage

2017-04-19 15:44 UTC, asundukov commented
зачем опять огромный реквест, как минимум тесты можно было вынести в другой  PR

2017-04-20 08:12 UTC, asundukov requested changes
ну пока вкратце отписал

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +    static {
почему в тестах решил заиспользовать именно static вместо BeforeClass?

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +        checkIndexSet(clonedEntriesMap.keySet());
вообще идеально: один тест - одна проверка
можно ли в тестах проверять только один набор элементов, и сделать отдельный тест на проверку что наборы совпадают? тогда и методы не нужно будет дублировать по названиям.

то же самое и про остальные тесты в классе

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +    void checkLinks(Map<Integer, GraphEntry> mapToCheck) throws Exception {
private

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +    private final static String allFeaturesFilename = "src/test/resources/XMLLoaderTest/AllFeatures.xml";
путь должен быть относительным от рута тестовых ресурсов, если не получается - надо поискать где он прописывается централизовано для проекта.

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +    void checkLinks(Map<Integer, GraphEntry> mapToCheck) throws Exception {
в идеале в каждом тесте должно быть 3 явнопрослеживаемые части:
1. установка окружения для теста
1. вызов тестируемого метода
1. проверка результата

тут сейчас сложно рассмотреть что мы делаем и что тестируем

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +        QuestionNode nextNo = (QuestionNode) fieldNextNo.get(mapToCheck.get(10).getNode());
навскидку выглядит будто можно выделить метод getInaccesibleField

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +public class XMLLoaderTest {
юнит тесты тестируют классы. Этот юнит тест тестирует набор классов. Все критерии чистого кода применимые к основному коду - они применимы и к тестам, а это значит что один класс - одна зона ответственности. Тут сейчас невнятная зона ответственности. Иногда пишут отдельный класс для тестирования одного метода, а тестировать набор классов - это либо невнятное что-то тестируем.

Если же хотим тут сделать какой-то интеграционный тест - то лучше это указать в названии теста или пекейджа.
Если же вдруг хотим протестировать несколько классов в каком-то одном пекейдже (какой-то сервисный тест бизнес-логики размазанной по нескольким классам) - то тогда пекейдж теста должен совпадать с пекейджами классов - тогда из тестов сможем получить доступ к package-private полям класса. Хотя кейс "логика размазанная по нескольким классам" - это тоже какой-то запашок. Тогда надо выделить рабочий класс компонующий в один всю размазанную логику и уже его протестировать юнит-тестом.

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +            e.printStackTrace();
В тестах лучше так не делать. когда тестов будет много и инфы в консоли - тоже, стектрейс просто пропустишь. Лучше чтоб тест падал в месте ошибки, чем где-то еще.

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +        assertTrue(variants.get(0).equals("Первый вариант"));
посмотри на тему assertThat и мэтчеров.

будет выглядеть примерно так:
assertThat(variants, contains("Первый вариант", "Второй вариант"));

удобно и читабельней :)

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +        assertTrue(mapToCheck.get(4).getNode().getQuestion().getText()
`mapToCheck.get(num).getNode().getQuestion().getText()` - это тоже дублирование, затрудняет чтение кода

2017-04-20 08:12 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/xml/loader/XMLLoaderTest.java
> +        assertTrue(mapToCheck.get(4).getNode().getQuestion().getText()
и тут вместо assertTrue лучше использовать assertEquals (и вообще везде где сравниваются объекты) - тогда при падении в тесте ты увидишь не expected true / actual false, а expected "Верный текст" / actual "Проверяемый текст" - гораздо больше инфы чтоб сразу понять в чем дело

это же к остальным относится.

ну или как вариант - везде использовать assertThat - тогда и проверки можно будет читать почти на инглише + там очень много мэтчеров для очень разных ситуаций есть и они все будут выводить инфу в консоль в удобном виде при падении теста.

2017-04-20 08:12 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +                log.error("Error parsing XML");
а тут вообще лучше тоже кидануть Runtime какой-нибудь или выше прокинуть. Иначе на старте не загрузится граф, т.к. parse вызывается из static init, но сервис стартанет и будет на каждой реквест от пользователя падать с NPE где-то. В итоге и мониторинги не скажут что сервис лежит и пользователи не получат его в рабочем состоянии.

2017-04-20 08:12 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +                log.error("Error parsing XML");
и вообще кончайте ловить ошибки в лог и не обрабатывать их :)

2017-04-20 08:12 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +    static GraphEntry fromXMLEntry(XMLEntry xmlEntry) throws IOException {
все еще грусть.

2017-04-22 23:33 UTC, khasanovbi requested changes

2017-04-22 23:33 UTC, khasanovbi commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +        Constructor<GraphEntry> constructor = GraphEntry.class.getDeclaredConstructor(args);
Тут можно проще сделать getDeclaredConstructor(QuestionNode.class, Map.class)

2017-04-22 23:33 UTC, khasanovbi commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private static Graph sampleGraph;
Лучше это назвать expectedGraph, ты же тестишь совпадение распарсенного XML и это ты ожидаешь увидеть. BeforeClass бы еще сюда.

2017-04-22 23:40 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
Есть стандартые java интейрфейс Clonable и метод clone у Object.

2017-04-24 08:33 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
Это в джаве косячная система. Интерфейс Clonable пустой, и контрактов на него вроде бы нет.

Метод Clone возвращает Object, и при вызове каждый раз тип приводить не хочется.

2017-04-24 09:30 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
Да в интерфейсе ничего не сделано, но это стандартная тулза, в джаве соглашение такое, иначе все объекты были бы Clonable. Как правило надо переопределять clone на публичный, если нет Clonable, то зарейзится ошибка. Имхо если есть стандартный метод, то лучше его заюзать, он будет понятен другим джавистам, это не критично, можно оставить в техдолге. Но BeforeClass до сих пор нет в тестах

2017-04-24 09:33 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
Что в BeforeClass-то писать? Подготовки-то нет никакой.

2017-04-24 09:41 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
Мне не нравится статическое создание графа при инициализации класса. Правильно было бы готовить граф либо в тесте, либо автоматически с BeforeClass, тесткейс еще не запускался, а граф уже инициализирован

2017-04-24 10:09 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +    public QuestionNode cloneContent() {
понял, поправлю

2017-04-24 10:15 UTC, asundukov requested changes
кстати про рут ноду идея - если вынести атрибут рутовой ноды на уровень выше в XML в виде rootNodeId-атрибута, то не нужно будет делать валидацию на count под количество этих нод, останется только requierd-атрибут - а это куда проще и логичнее.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/cv/builder/PlainTextCVBuilder.java
> +        return "not implemented yet";
тогда еще лучше явно указывать todo в комменте и еще номер или ссылку на заведенную задачу.
todo чтоб можно было поиском всегда по проекту найти, номер задачи - чтоб эту туду не забыли сделать в ближайшее время.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/Question.java
> +    }
типичный хешкод - порядкозависимый для списков, а это значит что у тебя на разные хешкод будут совпадающие по equals объекты. А это очень очень плохо.

вот можно почитать подробнее https://habrahabr.ru/post/168195/

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +package ru.hh.resumebuilderbot.question.storage.graph;
классы отредактированные и переименованные в рамках одного пулл-реквеста просматривать потом - адский ад :( если они гитом превращаются в удаление + добавление. В идеале конечно разные пуллреквесты. Можно в одном пуллреквесте но если коммитов 2-3 штуки. в 22+ коммитов смотреть не полезут люди.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/Question.java
> +    }
и вообще, если реализация, которая обычно бывает дефолтной, переделана в нестандартный вариант - лучше оставить подробный коммент почему так сделано. Иначе люди потом словят неожиданное поведение стандартных методов, и не смогут сходу найти. А на equals и hashCode завязана работа всех коллекций, например.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +    public boolean equals(Object o) {
аналогично тому что писал выше

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +                                              Question question) {
я вижу три метода с одинаковой сигнатурой, я тут не вникал, но для меня это маячок того что что-то пошло не так. Возможно стоит убрать статичность, превратить в поля класса и сделать код чище.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +    public boolean equals(Object o) {
и тут

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +        Document document = null;
= null не обязательно

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +        try {
а если весь try вынести в другой метод - то не нужно будет объявлять переменную без значения и код станет чище. - метод не будет делать "то-то И ловить эксепшн". можно будет сказать что он делает "то-то", а это уже ближе к SPR что хорошо.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +        try {
к обоим try в методе относится.

2017-04-24 10:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLValidator.java
> +        // step 2 - check ids' uniqueness
2 шага - два подметода, явно же сам разделил, зачем писать комменты если можно написать название метода?

2017-04-24 10:15 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +
2 пустые строки?

2017-04-24 10:15 UTC, asundukov commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +        entriesMap.put(9, graphEntry);
сам же метод на блоки разбил праивильные, почему и в меньшие методы не вынести все? если не выносится - то что-то не так. Вообще тут весь метод про построение графа, возможно стоит вынести его в класс типа тестграфбилдер.

2017-04-24 10:17 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +                                              Question question) {
Это подготовка к созданию унифицированного метода, как я понимаю.

2017-04-24 10:18 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/Question.java
> +    }
Мне нужен equals, но наш чекстайл при наличии equals требует еще и hash-код. Поэтому hashCode я дефолтный оставил.

2017-04-24 10:18 UTC, KhasanovBI commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
вроде у тебя тест не должен пройти, потому что метод должен быть static

2017-04-24 10:20 UTC, Trympyrym commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
Это в JUnit должен быть статиком. У нас TestNG. (Не знаю почему, я в зависимостях ничего не менял). В нем тесты проходят и так.

2017-04-24 10:23 UTC, KhasanovBI commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
Очень странно... Можешь заребейзить мастер, плз, там в travis запуск тестов есть.

2017-04-24 10:25 UTC, KhasanovBI commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
Странно, что аннотации подтянулись другие.

2017-04-24 10:29 UTC, Trympyrym commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
забирай

2017-04-24 10:32 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +                                              Question question) {
Это все еще подготовка. После этого PR будет еще один, где этот кусок переделан.

2017-04-24 10:36 UTC, khasanovbi approved these changes

2017-04-24 10:38 UTC, khasanovbi commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
Ну ок, раз прошли, но это какая-то магия)

2017-04-24 10:47 UTC, KhasanovBI commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +    private void createExpectedGraph() throws Exception {
А... Я думал в зависимостях JUnit.

2017-04-24 12:49 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/Question.java
> +    }
Предлагаю в тех. долге оставить. Понятно, как надо переделывать, но это долго, стремно и сейчас не требуется.

2017-04-24 12:56 UTC, Trympyrym commented on src/test/java/ru/hh/resumebuilderbot/question/storage/graph/GraphTest.java
> +        entriesMap.put(9, graphEntry);
Тестовый граф создавался таким образом, чтобы разные ноды были максимально различные по структуре. Поэтому код создания каждой ноды немножко разный. Т.е. если выносить создание ноды в отдельный класс, то у него будет либо много конструкторов, либо столько же сеттеров. В целом качество кода, конечно, выиграет, но это долго, стремно и предлагаю в тех долге оставить.

ТестГрафБилдер сделал, все создание графа в него перенес.

2017-04-25 08:31 UTC, asundukov requested changes

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +                                              Question question) {
грусть

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +        boolean result = getNode().hasEqualContent(that.getNode()) &&
почему не equals?

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLValidator.java
> +                throw new RuntimeException("Error: wrong XML schema - duplicate node index");
нашел дублирующийся елмент но не выдал его id.
можно либо упростить код, либо выдавать все дубли (но код все равно упростить).

в первом случае - вызываешь конструктор множества и передаешь ему список айдишек с помощью стрима (а стрим еще лучше в подметод вынести) - будет множество из элементов. и потом сравниваешь их размеры.

во втором случае - дополнительно к первому случаю делаешь diff между коллекциями и получаешь список дубликатов. Возможно можно и с помощью одного стрима - но это уже нечитабельно будет.

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +            throw new RuntimeException("Error parsing XML. Maybe XML is not valid");
вообще все Exception принимают еще один параметр Exception e передать информацию об ексепшене выше по стектрейсу и на самом верху вывести не только последний эксепшн, а всю цепочку "киданий-ловлений" этих исключений.

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLEntry.java
> +    private static Question makeQuestion(Optional<Node> optionalQuestionNode) {
зачем? принимай нормальный тип.

в вызывающей стороне можно оставить `optionalQuestionNode.orElse(null)`

2017-04-25 08:31 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLEntry.java
> +        if (optionalQuestionNode.isPresent()) {
развренув if можно будет убрать else и совместить объявление questionNode с init-значением

2017-04-25 08:57 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/GraphEntry.java
> +        boolean result = getNode().hasEqualContent(that.getNode()) &&
Я понимаю equals() как метод, детектирующий равенство объектов с точки зрения их прямого использования (по назначению). Таким использованием для нод является процесс движения по ним пользователя. С такой точки зрения линки в нодах (одна в линейной и две в ветвящейся) обязаны входить в equals. Поэтому при сравнении GraphEntry нужно использовать другой метод, который детектирует равенство содержимого без ссылок на другие ноды. Как-то так я думал при написании кода.

2017-04-25 14:14 UTC, asundukov requested changes

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/Question.java
> +        return Objects.equals(getText(), that.getText()) && variantsOfAnswer.equals(that.variantsOfAnswer) &&
почему equals не через Object ? NPE же потенциальная

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +        for (Map.Entry<Integer, GraphEntry> entry : entriesMap.entrySet()) {
тоже в другой метод, уровень абстракции другой

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +        for (Map.Entry<Integer, GraphEntry> entry : entriesMap.entrySet()) {
да и вообще по негласному соглашению конструктор просто берет и записывает себе переданные объекты, а не их копии. Копирование надо вообще вынести до конструктора. Иначе создаешь неожидаемое поведение.

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +        return result;
Может так?
```
return rawData.stream.collect(Collectors.toMap(XMLEntry::getIndex, xmlEntry -> GraphEntry.fromXMLEntry(xmlEntry)));
```
не знаю очевиднее ли получилось, на твое усмотрение.

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +        entriesMap.values().forEach(x -> x.setLinks(nodesMap));
что-то мне это не нравки.

может setLinks перенести на другой уровень? по сути на уровень nodesMap, а тогда уже и на уровень entriesMap - и как правильно уже замечали - его следовало вынести в отдельный класс и тогда он был бы легко расширяем и по одному вызову делал бы линковку энтрей, без необходимостей рассказывать каждой из них обо всем графе.

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeForking.java
> +                && that.isSkippable == isSkippable && that.answerPattern.pattern().equals(answerPattern.pattern());
чисто эстетически - мне кажется если уж переносить то переносить все условия

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +        if (!(questionNode instanceof QuestionNodeLinear)) {
какие-то первые строки у этих методов прям одинаковые, в глаза бросается

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLEntry.java
> +            return result;
если возвращаем иммутабельный объект - то лучше вернуть Collections.emptyMap() здесь, а определение result сделать ниже - ближе к прямому использованию.

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLEntry.java
> +    private static void parseLink(Node src, Map<String, Integer> dest) {
мутабельный параметр - фуфуфу

2017-04-25 14:14 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/xml/parser/XMLParser.java
> +            throw new RuntimeException("Error parsing XML. Maybe XML is not valid");
тут все еще

2017-04-25 16:56 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/node/QuestionNodeLinear.java
> +        if (!(questionNode instanceof QuestionNodeLinear)) {
Нихт ферштейн. У hasEqualContent?

2017-04-25 17:27 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/question/storage/graph/Graph.java
> +        entriesMap.values().forEach(x -> x.setLinks(nodesMap));
EntriesMap в отдельный класс вынесу, это пригодится. По поводу линковки либо я тебя не понял, либо фигня получается.

2017-04-25 21:19 UTC, asundukov approved these changes
ну либо все ок, либо глаз замылился и все равно что-то упускаю :)

в очередной раз призываю делать более короткие пулл-реквесты - а то смотрю код и не понимаю к конкретно с какой целью менялась каждая строчка - и сложно оценивать эффективность такой замены.

2017-04-26 06:29 UTC, merged