42 inline mode
hh-school/bot-resume-builder pull request #29
Opened 2017-04-21 12:47 UTC by savinsergey

Добавлены все подсказки в inline мод
Слегка переделана структура класса Adapter
Класс BotImpl перенесен в отдельный файл

2017-04-21 12:52 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +    public QueryResultsGenerator(InlineQuery inlineQuery) {
почему бы это не передавать не в конструкторе, а в `getResults`, можно было бы не создавать такой объект на каждый результат.

2017-04-21 12:54 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +    private final static String institutesUrlRequest = "https://api.hh.ru/suggests/educational_institutions";
Может лучше просто ...Url без Request.

2017-04-21 14:50 UTC, Trympyrym requested changes

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    void askNextQuestions(User user, Answer answer);
Чет не понимаю, зачем тут переименовывать

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +        String currentState = "2"; //getCurrentState(chatId);
Слишком много хардкода в одном месте

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +    public static List<Map<String, String>> getFaculties(String instId, String searchQuery) {
может, инкапсулировать это дело? Как-то не очень List<Map<String, String>> туда-сюда гонять.

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +    public static List<Map<String, String>> getFaculties(String instId, String searchQuery) {
Сюда же хорошо зайдет instituteHasNoFaculties

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +        for (JsonElement faculty : faculties) {
Парсинг json-а вынести бы в отдельный класс. Здесь в каждой строке .get().getAsString() плохо смотрится

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +        errorResult.put("text", "Ничего не выбрано");
Здесь бы к TextsStorage обращаться. Оно как раз для таких сообщений и сделано.

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
get что? непонятно, что метод делает. (ко второму гету это тоже относится)

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +                query.append("?");
Тут магия. Символы "?" и "&" хотя бы в локальные переменные загнать надо.

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +                    query.append(String.format("%s=%s&",
Тут просится что-то вроде addParam(querry, paramName, paramValue)

2017-04-21 14:50 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/BotImpl.java
> +        if (telegramAnswer != null) {
(Не критично) Мне кажется, надо telegramAnswer переименовать в telegramReaction (фабрику, соответственно, тоже). И переделать фабрику, чтоб всегда валидный класс-обработчик апдейта выдавала.

2017-04-21 15:02 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
это метод http get, я не понимаю, как более очевидно его назвать

2017-04-21 15:04 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
С этим согласен с @savinsergey, но я бы класс переназвал в HTTPClient какой-нибудь)

2017-04-21 15:08 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    void askNextQuestions(User user, Answer answer);
Метод с названием answer() по семантике должен отвечать, а мы наоборот ответ обрабатываем и задаем новые вопросы. Не придумал имени лучше, можем обсудить.

2017-04-21 15:09 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +        String currentState = "2"; //getCurrentState(chatId);
блок свитч-кейс изменится, как только определимся, откуда брать инфу о необходимой подсказке

2017-04-21 15:17 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
Метод должен делать что-либо и называться соответствующе. Здесь получается метод "получить". Что получить? Непонятно. Нормальные названия гет-методов ([из джавадокса](https://docs.oracle.com/javase/tutorial/java/javaOO/methods.html)) - getBackground, getFinalData. Так что нужно понять, что этот гет выдает, и соответственно изменить название.

Аналогия с http-гетом не канает, ибо тут путаница в терминологии. "метод" в http-протоколе и в java - это две большие разницы. Метод в http - это тупо строка ([пруф ](https://ru.wikipedia.org/wiki/HTTP#.D0.9C.D0.B5.D1.82.D0.BE.D0.B4.D1.8B))

2017-04-21 15:18 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    void askNextQuestions(User user, Answer answer);
Хм. Ну ок.

2017-04-21 15:18 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +        String currentState = "2"; //getCurrentState(chatId);
Ок

2017-04-21 15:20 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
Про переименование класса в HTTPClient - поддерживаю.

2017-04-21 15:33 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/URLRequest.java
> +    public static String get(String url, Map<String, String> queryParams) {
В рамках http клиента думаю и так было бы понятно, что get делает, если бы были еще и методы put, post, имхо. Как вариант можно sendGet, sendPost.

2017-04-21 15:41 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +        for (JsonElement faculty : faculties) {
Возможно стоит заимплементить тип, заюзав JsonDeserializer, как предложение.

2017-04-21 16:00 UTC, Trympyrym requested changes

2017-04-21 16:00 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +        for (int i = 0; i < rowData.size() && i < 50; i++) {
Магия. Откуда 50?

2017-04-21 16:00 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +    private static List<InlineQueryResult> getResultsFromRowData(List<Map<String, String>> rowData) {
Что такое rowData? Если что-то типа "сырые данные", то наверное rawData. Если это данные строки, то почему они в list-е?

2017-04-21 16:00 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +            queryResult.setTitle(rowElement.get("title"));
Внутренности цикла бы в отдельный метод вынести.

2017-04-21 16:00 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    public static String sendGetRequest(String url, Map<String, String> queryParams) {
Мне не нравится 2 public метода с похожей сигнатурой. Один надо приватным сделать. Извне вызывать тот, в котором больше параметров.

2017-04-21 16:00 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    private static String addQueryParameter(String url, String param, String value) {
Надо бы запилить что-то типа RequestBuilder (что-то типа StringBuilder, но для реквестов). С методами append(String paramName, String paramValue), append(Map<String, String> params) и toString()

2017-04-21 16:14 UTC, Trympyrym requested changes

2017-04-21 16:14 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +            conn.setRequestProperty("User-Agent", "Mozilla/5.0");
Мозилла? А можно ее заменить на что-то типа "HH-ResumeBuilderBot/0.2" ? Если веб-сервис позволит, было б неплохо.

2017-04-21 16:14 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +                result.append(line);
Не уверен, но LineSeparator не потеряется тут?

2017-04-21 16:14 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    public static String sendGetRequest(String urlToRead) {
(Не критично) Метод называется "отправить запрос". При этом он открывает соединение и читает данные из стрима. А запрос не отправляет. Что-то тут не так.

2017-04-22 11:02 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    public static String sendGetRequest(String url, Map<String, String> queryParams) {
Не согласен, оба метода неплохо смотрятся пабликами. Не вижу схожести, у одного 1 параметр, у другого 2, перепутать очень сложно. Ну и в твоем варианте чтобы сделать гет запрос без параметров, нужно вызывать метод с пустой мапой в качестве второго аргумента. Выглядит не очень.

2017-04-22 11:12 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    public static String sendGetRequest(String url, Map<String, String> queryParams) {
Ок, этот пункт проехали.

2017-04-22 13:38 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +        for (JsonElement faculty : faculties) {
Тут в половине случаев уникальное строение Json, писать 5 имплементаций ради того, чтобы смотрелось чуть-чуть красивее?

2017-04-22 13:55 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +                result.append("\n");
System.lineSeparator() или как-то так. Не надо /n

2017-04-22 13:55 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +/**
кхм. убрать автотекст

2017-04-22 13:55 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/QueryResultsGenerator.java
> +//        Question currentQuestion = UserDataStorage.getCurrentQuestion(new User(chatId));
комментированный код тоже убрать

2017-04-22 15:09 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/HTTPClient.java
> +    private static String addQueryParameter(String url, String param, String value) {
Либо заюзать готовый HTTPClient, чтобы не городить велосипедов, например, такой:

<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.5.3</version>
</dependency>

2017-04-22 17:49 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/queryresults/generator/SuggestGenerator.java
> +        for (JsonElement faculty : faculties) {
Дело не в том чтобы смотрелось лучше. 
1) это позволит разбить код на куски, сейчас это большой скоуп из разных парсеров, 
2) можно было бы сразу обернутый объект получать.

2017-04-22 19:16 UTC, Trympyrym approved these changes

2017-04-22 20:09 UTC, merged