7 application skeleton
hh-school/bot-resume-builder pull request #3
Opened 2017-03-10 07:18 UTC by asdzxcasd

Добавил скелет приложения

2017-03-10 08:35 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
Бот не слушает messengerAPI. messengerAPI сам дергает метод answer() бота, когда присылает ответ. Так сильно проще получится

2017-03-10 09:13 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
все верно, это должно выглядеть примерно так:
```
apiBridge.setIncomingMessageHandler(new MessageHandler());
```
а класс MessageHandler содержит метод
```
public void handle(int chatId, String message) {
  Thread thread = new Thread(() -> {
    // something processor for chatId & message
  });
}
```
внутренности apiBridge сами занимается прослушиванием новых сообщений и дергают метод handle. В java-либах под телеграм-бота такие штуки должны быть реализованы уже.

2017-03-10 09:15 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
В принципе тут почти верно, только по идее start() переименовать в handle с приемом двух параметров а сам экземпляр BotBody передавать в какой-то класс. Но конечно логичнее и эти операции разнести еще по классам.

2017-03-13 16:56 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
Я правильно понимаю, что под apiBridge подразумевается какой-то сторонний класс, который умеет работать с сервером телеграма?

2017-03-13 17:27 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
Сейчас есть интерфейс AbstractBotBody. Для чего тогда ещё MessageHandler? Кажется, что получается одно и то же.

2017-03-13 19:19 UTC, asundukov requested changes

2017-03-13 19:19 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Interfaces.java
> +class Question {
1 файл - 1 класс/тип/енум/интерфейс. Не надо вот так лепить все в одну кучу.

2017-03-13 19:19 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +        // connect to job site
че то я сомневаюсь что здесь нужен будет коннект к джоб сайту - к нему коннектиться надо будет в время клиентских подключить отдельными http(s) запросами к API. Ни один джоб сайт вроде не поддерживает перманентно висящий коннект.

Ну или может чтоб путанницы не было здесь стоит называть не коннект к джоб сайту а какая-то инициализация конфигов.

2017-03-13 19:19 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +        MessengerAdapter messenger = new ConsoleMessengerAdapter();
лучше переменную так и назвать messengerAdapter. А то чуть ниже по коду без контекста просто messenger уже сбивает с толку. Такие штуки ко всему коду относятся. Представляй что ты будешь потом читать код не видя строчки инициализации переменной. Ее имя должно сообщать тебе нужную информацию о ее назначении, а в идеале еще и о типе.

2017-03-13 19:19 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
окей, пусть будет messenger.setHandler(this). Я к тому что с while(true)  в отдельном треде - это явный антипаттерн [Busy waiting](https://en.wikipedia.org/wiki/Busy_waiting. У нас ОС знает когда придет реквест от сервера телеграма - тогда тред слушающий сокет узнает что пришли данные, обработает их и  сам дернем метод  ask твоего AbstractBotBody.

2017-03-13 19:19 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +        messenger.setListener(bot);
и все же тут у меня в голове возникает чувство алогичности. почему нам сначала требуется в bot передать messenger, а потом еще messenger'у передать экземпляр bot - он разве сам не может этого сделать при создании?

2017-03-14 00:11 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +            while (true) {
Но тут же не busy waiting. Поток блокируется, если очередь пуста. Когда дёргается метод onAnswer, он продолжает выполняться.
Хотя с тем, что здесь не нужно отдельного потока, согласен, да.

2017-03-14 00:29 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +        // connect to job site
Да, наверное так. Я предполагал, что тут будет подключение к адаптеру джоб сайта, который уже сам будет разруливать это. Хотя сейчас начинает казаться, что и это будет лишним.

2017-03-14 07:18 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Main.java
> +        // connect to job site
да, в идеале все инициализации спускать лучше как можно ниже по стеку - так будет проще в будущем покрывать тестами код и подменять реализации если вдруг это потребуется

2017-03-14 09:27 UTC, asundukov requested changes

2017-03-14 09:27 UTC, asundukov commented on docs/how-to-run.md
> +2. запуск из IntelliJ IDEA
не `2.`, а `1.`

2017-03-14 09:27 UTC, asundukov commented on resumebuilderbot.iml
> +</module>
в конце всех файлов лучше добавлять EOL. Так при выводе cat через консоль последняя строка будет правильно отображаться. Ну и обычно это требование в codestyle тоже добавляют.

2017-03-14 18:17 UTC, Trympyrym commented
Сквош коммитов будет?

2017-03-14 18:18 UTC, Trympyrym requested changes
Сквош коммитов будет?

2017-03-14 18:20 UTC, asdzxcasd commented
Да, думаю, что лучше со сквошем. Вроде можно непосредственно при мердже сделать.

2017-03-14 20:07 UTC, asundukov requested changes
не все классы разнесены по файлам еще

2017-03-14 20:07 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Question.java
> +//    private List<String> allowedAnswers;
закомментированный код - это плохо, он вводит в заблуждение - почему закомментирован, что автор хотел этим сказать, можно ли его использовать или надо еще что-то сделать. Ладно мы мы на встрече были и может в курсе, а кто-то новый будет читать - придется к автору обращаться

2017-03-14 20:07 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Question.java
> +class Question {
все еще несколько классов в файле

2017-03-14 20:07 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Question.java
> +    // Начать принимать ответы пользователя
ну и эти комменты все же наверное не несут полезной информации, этого тоже лучше избегать

2017-03-14 20:07 UTC, asundukov commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
тут как предложение - может не будем использовать XML для конфигов ? они слишком избыточно и большие файлы сложно читаются человеком. Есть более "человечные" `.properties` файлы.

2017-03-14 20:07 UTC, asundukov commented on resumebuilderbot.iml
> +<?xml version="1.0" encoding="UTF-8"?>
да и кстати, iml-файлы это вроде бы вообще файлы настроек конкретной среды разработки. К пректу они обычно слабо относятся, а вся нужная инфа для этого должна содержаться в pom-файле. Посмотри, пожалуйста, тоже нужен ли нам этот файл в репозитории.

2017-03-14 21:14 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/Question.java
> +class Question {
чёрт, я умудрился не закоммитить половину файлов, сейчас исправил

2017-03-14 21:55 UTC, asdzxcasd commented on resumebuilderbot.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Попробовал удалить файл и создать проект в IDEA из `pol.xml` заново, вроде всё работает. Поскольку .iml файлы генерируются автоматически, то наверное и правда лучше их убрать. Нужно будет дополнить `how-to-run`.

2017-03-14 21:55 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/Question.java
> +//    private List<String> allowedAnswers;
написал комментарий, что нужно добавить эти поля

2017-03-14 23:04 UTC, asdzxcasd commented on src/main/resources/hibernate.cfg.xml
> +<hibernate-configuration>
Да, кажется, что `.properties` удобнее будут.

2017-03-14 23:48 UTC, asundukov approved these changes

2017-03-15 05:44 UTC, merged