TestMessengerAdapter added
hh-school/bot-resume-builder pull request #4
Opened 2017-03-11 18:12 UTC by Trympyrym

2017-03-13 18:15 UTC, asdzxcasd requested changes

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/Readme.md
> +��� �������� ���: ����� ��� ������� �� ����� ask(), �� ���� ��� ���������� ������ ��������� ������� � ���������� �� �����. ���� ���� ���� ���������, �� �������� ��������������� ����� ������. ���� ���
Лучше сохранять файлы в кодировке utf-8, чтобы везде правильно отображались. Сейчас кодировка windows-1251.

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/TestMessengerAdapter.java
> +        }
Можно вместо candidates.isEmpty() проверять maxRandomValue == 0, чтобы учитывать случай, когда все веса оказались нулевые.

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/TestMessengerAdapter.java
> +        int randomValue = rng.nextInt(maxRandomValue + 1);
Чтобы получилось равномерное распределение с вероятностями, пропорциональными весам, нужно вызывать `rng.nextInt(maxRandomValue)`, а также условие ниже заменить на `counter > randomValue`.

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/TestMessengerAdapter.java
> +    }
getWeightedRandomAnswer возвращает первый ответ чаще, чем его вес. Например, если есть два ответа с весом 1, то первый будет выпадать в 2 раза чаще. Не критично, но потом может всплыть в самый неподходящий момент.

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/Loader.java
> +}
Открывающиеся фигурные скобки стоят как в конце строки, так и на отдельной строке. Лучше, чтобы было единообразно. Предлагаю ставить скобки на той же строке (K & R style), чтобы не растягивать сильно код по вертикали (на ноутбуке, например, неудобно просматривать). И да, хорошо бы обсудить и определиться с code style.

2017-03-13 18:15 UTC, asdzxcasd commented on TestMessengerAdapter/config.txt
> +weight=1
Я бы использовал здесь JSON вместо текстового файла даже для такого простого конфига. JSON получается более структурированный и его проще распарсить, однако многострочные поля в нём сделать не получится.
Если всё-таки оставлять текстовый файл, то вопросы лучше отделять друг от друга пустой строкой, чтобы они не сливались.

2017-03-13 18:18 UTC, Trympyrym commented on TestMessengerAdapter/config.txt
> +weight=1
можно и отделять. парсер строки между вопросами не смотрит

2017-03-13 18:22 UTC, Trympyrym commented on TestMessengerAdapter/TestMessengerAdapter.java
> +        }
Не надо указывать нулевые веса

2017-03-13 18:32 UTC, Trympyrym commented on TestMessengerAdapter/config.txt
> +weight=1
Ответ TestMessengerAdapter имитирует ответ пользователя. Некорректно лишать его многострочности.

2017-03-13 19:00 UTC, asundukov commented on TestMessengerAdapter/TestMessengerAdapter.java
> +/**
вот эти автокомменты лучше вырезать вообще из шаблонов файлов - они всех бесят и не несут никакой полезной информации (и метаинформации) для кода.

а авторство навсегда остается в системе контроля версий

это касается всех файлов в пулл-реквесте.

2017-03-13 19:00 UTC, asundukov commented on TestMessengerAdapter/Loader.java
> +        else if (currentState == State.READING_QUESTION)
код с кучей if и else if - это код "с запашком" и с большой возможностью в будущем превратиться в "спагетти код". В данном случае внутренние блоки лучше вынести в функции с названиями, которые читающему код будут сразу давать контекст происходящего, а в данной функции не будет спусков на более низкий уровень абстракции. 
Можно почитать на тему "принцип единственное ответственности" и там будут хорошие примеры приведения кода к более понятному структурному виду.

вообще 80% времени код мы читаем, и только 20% пишем - поэтому очень важно писать такой код который можно будет быстро читать, даже если на его написание уйдет в 2 раза больше времени.

2017-03-13 19:00 UTC, asundukov commented on TestMessengerAdapter/Readme.md
> +1) Вызвать конструктор с единственным параметром - именем файла с базой вопрос-ответ
в github markdown для нумерованных списков есть специальные "тэги" - если начинать строку с `1.` то каждая новая строка будет нумероваться следующим номером.

2017-03-13 23:14 UTC, asdzxcasd commented on TestMessengerAdapter/TestMessengerAdapter.java
> +/**
изменяется вот так: https://www.jetbrains.com/help/idea/2016.3/creating-and-editing-file-templates.html во вкладке Includes

2017-03-13 23:27 UTC, asdzxcasd approved these changes

2017-03-13 23:33 UTC, asdzxcasd commented on TestMessengerAdapter/TestMessengerAdapter.java
> +        }
Это стоит явно написать в комментах/документации, потому что неочевидно

2017-03-13 23:46 UTC, asdzxcasd commented on TestMessengerAdapter/Loader.java
> +        else if (currentState == State.READING_QUESTION)
а ещё тут вполне подошёл бы switch

2017-03-14 17:42 UTC, Trympyrym commented on TestMessengerAdapter/TestMessengerAdapter.java
> +        }
В ридми исправил целые числа на натуральные

2017-03-14 17:43 UTC, Trympyrym commented on TestMessengerAdapter/Readme.md
> +1) Вызвать конструктор с единственным параметром - именем файла с базой вопрос-ответ
Починил

2017-03-14 17:49 UTC, Trympyrym commented on TestMessengerAdapter/TestMessengerAdapter.java
> +/**
fixed

2017-03-22 23:15 UTC, ghost approved these changes

2017-03-23 01:11 UTC, asdzxcasd approved these changes

2017-03-23 05:26 UTC, merged