43 db services
hh-school/bot-resume-builder pull request #47
Opened 2017-05-05 10:00 UTC by savinsergey

Удален класс UserData
В UserDataStorage хранится id текущей вопросной ноды
Вся логика по сохранению данных теперь в Handler'ах
Убран доступ из UserDataStorage в граф вопросов и наоборот.

2017-05-05 10:57 UTC, khasanovbi requested changes

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/dao/AreaDAO.java
> +    public Area getAreaByHHId(Integer hhId);
public в интерфейсах не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/suggester/HTTPClient.java
> +            conn.setRequestProperty("TelegramUser-Agent", "HH-ResumeBuilderBot/0.2");
User-Agent

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/dao/UserDAO.java
> +    public User getByTelegramId(long telegramId);
`public` не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/dao/experience/CompanyDAO.java
> +    public Company getCompanyByHHId(Integer hhId);
`public` не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/service/AreaService.java
> +    public Area getAreaByHHId(Integer hhId);
`public` не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/service/UserService.java
> +    public User getUserByTelegramId(long telegramId);
`public` не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/service/experience/CompanyService.java
> +    public Company getCompanyByHHId(Integer hhId);
`public` не нужен

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +                            getDeclaredConstructor(UserDataStorage.class, Graph.class );
Пробел на конце. PS я бы точку в начало перенес, видишь что продолжение предыдущей линии, но дело вкуса.

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +                    return (MessageHandler) constructor.newInstance(userDataStorage, graphProvider.get());
graphProvider создает на каждый get копию графа. Если ты так и хотел, объясни плс, зачем.

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/TelegramUser.java
> +public class TelegramUser {
У меня все еще сохранилась мысль, что стоит использовать одного юзера из db моделей, но это на размышление.

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/dao/experience/CompanyDAOImpl.java
> +    private final static String COMPANY_BY_HH_ID = "FROM Company WHERE hh_id = :hh_id";
Просто для информации, в style гайдах рекомендуется обычно порядок private static final

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    @Column(name = "phone")
length=15

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
С какой целью EAGER?

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/education/Education.java
> +    @Column(name = "institution_id")
В sql тоже надо добавить.

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserDataStorage.java
>      private UserDataStorage(ServiceAggregator serviceAggregator, Provider<Graph> graphProvider) {
graphProvider в конструкторе, а не юзается

2017-05-05 10:57 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserDataStorage.java
>      private UserDataStorage(ServiceAggregator serviceAggregator, Provider<Graph> graphProvider) {
Класс надо переназвать, раз теперь он не хранит UserData, он теперь не Storage, не знаю как именно, как вариант DBProcessor.

2017-05-05 11:20 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Не разобрался, как получать данные с LAZY. Во все места, куда можно, пихал @Transactional, не помогало. Это временный хак, чтобы работало.

2017-05-05 12:21 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/education/Education.java
> +    @Column(name = "institution_id")
Добавил

2017-05-05 18:46 UTC, KhasanovBI commented
travis ругается на unused imports в UserDataStorage, который пока так и не переименован.

2017-05-06 11:16 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/TelegramUser.java
> +public class TelegramUser {
Посмотрев внимательнее кажется стоит этот класс тоже убрать и заюзать просто telegramId

2017-05-06 11:20 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Оставь // TODO в таком случае плс, чтобы не забыть.

2017-05-06 11:22 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/user/data/storage/UserDataStorage.java
> +        log.error("Не найдено образование для пользователя {} по id {}");
аргументов логирования не хватает

2017-05-06 11:28 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +        this.graph = graphProvider.get();
Тут все еще магия с графом, Selector создается один раз, то есть и граф тут создастся один раз, раньше как бы было хранилище графов и граф пытались достать из хранилища, если он есть и не копировать, возможно тут надо доработать LRU cache, но в другом PR

2017-05-06 17:48 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/TelegramUser.java
> +public class TelegramUser {
В принципе можно, но не уверен, что это правильно, уходим от абстракции

2017-05-06 19:16 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/TelegramUser.java
> +public class TelegramUser {
Для чего она нужна тогда?

2017-05-07 07:43 UTC, merged