Bot body class structure
hh-school/bot-resume-builder pull request #5
Opened 2017-03-16 14:59 UTC by Trympyrym

Trello: https://trello.com/c/1dK4tc84/17--

2017-03-16 21:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    private Map<ChatId, UserData> userData;
Вопрос, не к конкретному PR, просто на обсуждение.
Зачем класс ChatId?  Если для того, чтобы нельзя было подсунуть случайно какой-то другой Long в это место, тогда стоило бы сразу сделать generic из этого, чтобы не плодить такие классы.

```java
public class LongId<T> {
    private long id;

    public LongId(long id) {
        this.id = id;
    }

    public long getLong() {
        return id;
    }
}
```

2017-03-17 08:20 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    private Map<ChatId, UserData> userData;
Вот как раз тип айдишки чата я и хотел инкапсулировать. Не хочется его жестко к лонгу привязывать.

2017-03-17 13:17 UTC, asundukov reviewed
по самому коду кое-что откомментил.

пока неясен остается UserDataStorage - но с ним решим когда с базой смерджим.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/AnswerMessageHandler.java
> +        UserDataStorage.registerAnswer(answer.getChatId(), answer.getAnswerBody());
нельзя ли туда передавать сам answer вместо того чтоб передавать поля этого объекта?

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/AnswerMessageHandler.java
> +        return new QuestionGeneratorByNumber(UserDataStorage.getCurrentState(answer.getChatId()).getCurrentQuestion());
это хоть и укладывается в разумные 120 символов в строке, но тут я вижу:
1. вызов 3-х функций, одна из которых принимает параметр
1. создание 1 объекта с передачей данных в конструктор

не слишком ли жирно для одной строки кода? становится сложно прочитать / уловить логику.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/ClearAllAndStartMessageHandler.java
> +public class ClearAllAndStartMessageHandler implements MessageHandler {
глагол  в названии класса - признак того что что-то пошло не так. 
наличие And - тоже признак что что-то не так, т.к. само наличие And предполагает что мы в класс/функцию добавили более одной единицы функциональности.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +        parsers.put(Pattern.compile("/clearAllAndStart"), new ClearAllAndStartMessageHandler());
нужен нам вообще такой? как насчет сделать просто `/clear` - для очистки текущего резюме. А дальше идет "автоматический" start все равно. Тогда и "жуткое" название ClearAllAndStartMessageHandler превратится в более человечное ClearMessageHandler

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/MessageHandler.java
> +public interface MessageHandler {
тут я думаю самое время все MessageHandler вынести в package messagehandler - тут уже явная необходимость сгруппировать назрела

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/NextQuestionGenerator.java
> +public interface NextQuestionGenerator {
Next тоже сбивает с толку. Тогда уж лучше интерфейс QuestionGenerator, а название метода - generateNext.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/NextQuestionGenerator.java
> +public interface NextQuestionGenerator {
ну и да - все QuestionGenerator можно объединить в один пекейдж.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +    private final Map<Pattern, MessageHandler> parsers;
для обсуждения
я вижу что паттерн и хэндлер соотносятся как 1к1 и в принцпе между ними есть тесная связь - может быть добавить в MessageHandler метод isMacth(String answerText)?
из плюсов:
1. мы подвинем сам маркер ближе к хендлеру (в один файл), что удобнее при работе с хендлером
1. сможем расширять isMatch потом дополнительно например если команды будут динамические и принимать дополнительно какие-то параметры, или разные команды на один хендлер, или будет анализ текста еще. 
1. здесь Map заменится на чуть более просто и более читабельный List или Set

из минусов: 
1. сложнее наглядно посмотреть список всех паттернов
1. с учетом того что написал ниже - сложно будет не создавать объект если его фактически не будем использовать, хотя тут можно изучить вариант со static-методом

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +        parsers.put(Pattern.compile(".*"), new AnswerMessageHandler());
если оставлять такую реализацию - то Pattern.compile(string) в данном случае дублирующийся код - можно спустить его ниже в цикл, и код будет визуально чище

бонусом - при не Singleton реализации класса у нас будет меньше вызовов compile.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +        parsers.put(Pattern.compile(".*"), new AnswerMessageHandler());
ну и сюда же - необходимость создавать объекты (в данном случае хендлеры) и потом их не использовать говорит о том что что-то спроектировано не так - тут можно либо превратить работу класса в Singleton-режим, либо отделить проверку matches() и создание - это можно сделать, попробовав передавать в map тип Class. Тогда будет выглядеть так: `parsers.put(Pattern.compile(".*"), AnswerMessageHandler.class)` а потом уже создавать из этого объект если matches прошел.

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/StartMessageHandler.java
> +            return new FixedQuestionGenerator(TextsStorage.getText("AlreadyStarted"));
свободные висящие "сервисные" строки лучше в константы уносить сразу. Тут она "сервисная" потому что передается дальше в Storage. Тем более по коду уже вижу два использования

2017-03-17 13:17 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/StartMessageHandler.java
> +            return new QuestionGeneratorByNumber(0);
и тут тоже в данном случае хоть и очевидно - но MAGIC_NUMBERS - плохой прецендент для следующего программиста который скопипастит строчку и 0 заменит на 1.

2017-03-17 19:14 UTC, asundukov commented
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.

2017-03-22 23:10 UTC, ghost approved these changes

2017-03-22 23:10 UTC, Alexey-Trifonov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +        messengerAdapter.ask(nextQuestionGenerator.generateNext(answer.getChatId()), 1000);
слишком много next. Может стоит назвать questionGenerator вместо nextQuestionGenerator? Но это так, лишь бы придраться)

2017-03-22 23:10 UTC, Alexey-Trifonov commented on src/main/java/ru/hh/resumebuilderbot/ChatId.java
>      final long index;
Нужно добавить метод для получения index, надо для MessengerAdapter.

2017-03-22 23:10 UTC, Alexey-Trifonov commented on src/main/java/ru/hh/resumebuilderbot/TextsStorage.java
> +        instance.textsMap.put("Unknown", "Cant understand your message");
Стоит использовать русский язык

2017-03-23 01:23 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +    private static Map<Pattern, Class> parsers = Collections.synchronizedMap(new LinkedHashMap<>());
Тут Map получается избыточным, потому что поиск по Pattern не используется (во всяком случае сейчас), а вместо этого перебираются все элементы коллекции и ищется совпадение, так что достаточно обычного List, содержащего пары из шаблона и класса.
Ещё parsers наверное должен быть final.

2017-03-23 01:23 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +                    return (MessageHandler)entry.getValue().newInstance();
А нельзя ли для каждого шаблона хранить объекты класса MessageHandler вместо того, чтобы хранить классы? Похоже, что тогда можно будет обойтись без reflection.

2017-03-23 01:23 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/UserDataStorage.java
> +        return instance.userDataMap.get(chatId).getCurrentState();
Здесь нет синхронизации по UserData, хотя в registerAnswer она есть.

2017-03-23 01:23 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/message/handler/AnswerMessageHandler.java
> +        int currentQuestionNumber = currentUserState.getCurrentQuestion();
Если для одного и того же ChatId вызывается AnswerMessageHandler.handle, то возникает race condition: могут сгенерироваться два вопроса с одним и тем же номером.

2017-03-23 01:23 UTC, asdzxcasd commented on src/main/java/ru/hh/resumebuilderbot/QuestionsStorage.java
> +    public static QuestionsStorage instance = new QuestionsStorage();
Нужно изменить public на private и, наверное, добавить final.

2017-03-23 14:10 UTC, asundukov requested changes

2017-03-23 14:10 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +        messengerAdapter.ask(nextQuestionGenerator.generateNext(answer.getChatId()), 1000);
ну вообще да, там есть метод generateNext - он вполне себе говорит о том что он делает, тащить "next" в название переменной нет смысла

2017-03-23 14:10 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/TextsStorage.java
> +        instance.textsMap.put("Unknown", "Cant understand your message");
да, либо мы сразу делаем кросс-национальную и юзаем механизм переводов, либо делаем по-русски. Выпускаем на русский рынок поэтому имеет смысл сейчас сделать по-русски.

2017-03-25 12:15 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +                    return (MessageHandler)entry.getValue().newInstance();
Тут вроде бы есть несколько разных способов как эти хэндлеры сделать, но явного преимущества нет ни у одного. Пока что оставлю как есть.

2017-03-25 13:41 UTC, khasanovbi approved these changes

2017-03-25 13:41 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/AnswerMessageHandler.java
> +package ru.hh.resumebuilderbot;
Все handler так и напрашиваются в отдельный package)

2017-03-25 13:41 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/UserDataStorage.java
> +public class UserDataStorage {
Это лучше сервис назвать, чтобы соответствовало Service DAO,  и интерфейс сделать, чтобы сразу можно было нормальный класс реализовать и просто поменять.

2017-03-25 13:41 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +public class Selector {
Зачем создавать Selector под каждый вопрос, не было бы лучше создать его один раз и answer передавать в select. PS. В серверах обычно такая штука называется Dispatcher.

2017-03-25 13:41 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/BotBody.java
> +    private Map<ChatId, UserData> userData;
Ну можно 2 generic сделать. Это будет лучше, чем множество таких классов. Сейчас у нас в проекте только ChatId, потом еще будут еще какие-то id, и не хотелось бы видеть кучу классов с непонятным типом внутри. C названием LongId<Chat> сразу будет видно что за тип.

2017-03-25 13:47 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +public class Selector {
селектор один. работает через статичный метод select()

2017-03-25 13:48 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/AnswerMessageHandler.java
> +package ru.hh.resumebuilderbot;
они и так все в отдельном package

2017-03-25 13:48 UTC, Trympyrym commented on src/main/java/ru/hh/resumebuilderbot/UserDataStorage.java
> +public class UserDataStorage {
это (скорее всего) будет переработано после прикручивания базы данных

2017-03-25 14:18 UTC, merged