Handlers rework
hh-school/bot-resume-builder pull request #54
Opened 2017-05-13 15:19 UTC by savinsergey

Добавлена таблица Skill
Добавлены 2 хэндлера-обработчика inline мода

2017-05-13 19:38 UTC, khasanovbi requested changes

2017-05-13 19:38 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/di/GuiceProdModule.java
> +        bind(SkillService.class).to(SkillServiceImpl.class);
Для порядка надо на строчку выше

2017-05-13 19:38 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/database/HibernateMetadataFactory.java
> +                .addAnnotatedClass(Skill.class)
тут тоже было бы ок на строчку выше для порядка.

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +    SuggestHandler getSuggestHandler() {
1. Имя не подходящее, такое ощущение будто это доступ к объекту, а на самом деле создается объект.
2. Selector отвечал за выбор хэндлера на основании ответа, getSuggestHandler не используется в этом месте. Либо надо переделать Selector, чтобы в нем выбирался ChosenSuggestHandler, либо перенести код в отдельное место.

`getChosenSuggestHandler` аналогично.

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/BotImpl.java
> +            InlineQuery inlineQuery = update.getInlineQuery();
Опять получается куча разной логики, лучше поделить это по методам.

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/SuggestHandler.java
> +                neededSuggest != SuggestType.FACULTIES_SUGGEST) {
Это не круто так делать, представь, что у нас еще какие-то SUGGEST отличался от других, и тут была бы еще сложная логика, это сложно понять и поддерживать, поэтому лучше оставить разделенными на две функции базовую обработку и обработку факультетов. Если нужен агрегирующий метод, надо тогда вынести этот кусок в другую функцию.

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/converter/entity/CompanyTelegramConverter.java
> +                .setId(id.toString())
Теперь это уже не Converter, надо либо переименовать класс, либо проставление id вынести на другой уровень.

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/Skill.java
> +    public Skill(){
пройдись форматтером, тут нужен пробел

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/DBService.java
> +    private Specialization createNewSpecialization(String specializationName, Integer specializationHHId) {
`New` избыточно, у нас же не будет `createOldSpecialization`

2017-05-13 19:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/DBService.java
> +        User user = getUser(telegramId);
По хорошему эти манипуляции должны быть в сервисах, а не здесь. Это все можно было бы сделать в рамках одной транзакции

2017-05-13 19:50 UTC, khasanovbi requested changes

2017-05-13 19:50 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/ChosenSuggestHandler.java
> +                Integer instituteId = dbService.getInstituteHHId(telegramId);
Давай назовем это InstituteHHId, чтобы не путаться потом.

2017-05-13 19:50 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Handler - плохое название для класса, в моем понимании, Handler должен только уметь как-то обрабатывать запросы, возможно это вообще был бы интерфейс c методов handle, тут же получается, что все Handler умеет сохранять запросы, что имхо может быть не справедливо для всех обработчиков, ну и это TODO было как раз частично про это, `DBSaverHandler` было бы корректнее, хотя такой абстрактный класс кажется странным.

2017-05-13 19:54 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +    SuggestHandler getSuggestHandler() {
Я думал потом из selector сделать класс, хранящий и выдающий нужный хэндлер

2017-05-13 19:55 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/BotImpl.java
> +            InlineQuery inlineQuery = update.getInlineQuery();
Здесь же вроде из логики только получение аргументов геттерами для вызова метода. Или ты про обработку события update в целом?

2017-05-13 20:05 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/BotImpl.java
> +            InlineQuery inlineQuery = update.getInlineQuery();
про update в целом

2017-05-13 20:16 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/Selector.java
> +    SuggestHandler getSuggestHandler() {
Нужно до конца дорефакторить раз начал, либо убрать отсюда и как будет второй PR добавить это туда. Просто сейчас это не поэтапный рефакторинг получается, а незаконченный этап. Кстати скиллы тоже можно было бы отдельным PR.

2017-05-13 21:16 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/converter/entity/CompanyTelegramConverter.java
> +                .setId(id.toString())
Почему это не конвертер, если он конвертит из одной сущности в другую. Просто нам необходимо использовать порядковый id, а не тот, что мы достаем из HH. и задать id можно только конкретной реализации InlineQueryResult, интерфейсу нельзя. И либо нам зачем-то делать еще один набор классов-прослоек, каждый из которых умеет только сеттить айди и возвращать InlineQueryResult вместо конкретной реализации, либо оставить всё как есть.

2017-05-13 21:28 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
В принципе, кроме как в AnswerMessageHandler сохранение не используется, можно метод туда перенести. Но почти всем handler'ам необходим доступ к базе и графу для получения текущей ноды. Если есть идеи, как архитектурно это изменить, не сильно воротя код, жду предложений. Имхо сохранение ответа входит в понятие "обработка"

2017-05-14 00:17 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/converter/entity/CompanyTelegramConverter.java
> +                .setId(id.toString())
Потому что мы еще подкидываем ему id мы тут скорее что-то собираем уже, это не простая конвертация из одного в другое. Как вариант, можно возвращать InlineQueryResultArticle в данном случае, если когда-то понадобятся типизированное представление можно будет это тоже в generic еще тип добавить

2017-05-14 00:27 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Входит то входит, но это не значит, что любой handler сохраняет, я про это. Наверное, вынести в отдельный класс и юзать внутри, если этим методом многие другие пользуются.

2017-05-14 12:08 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Все хэндлеры сейчас используют бд и только один не использует граф(и то этот хэндлер не доделан). Я правда не понимаю, почему текущая архитектура плохая

2017-05-14 16:10 UTC, asundukov approved these changes
если работает то ок)

2017-05-14 16:10 UTC, asundukov commented on src/main/java/ru/hh/resumebuilderbot/DBService.java
> +        User user = getUser(telegramId);
этот класс вообще зло) никак не могу понять зачем он нужен)

2017-05-14 16:49 UTC, khasanovbi requested changes

2017-05-14 16:49 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/adapter/BotImpl.java
> +        handleUpdate(update);
Давай содержимое handleUpdate перенесем сюда. Зачем делать функцию с передачей обработки другой функции?

2017-05-14 16:49 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
То что сейчас у нас все хэндлеры используют бд не означает, что когда-нибудь не нужно будет добавить хэндлер, который не будет использовать БД и будет утечка абстракции. По идее хэндлер должен только обрабатывать как-то запрос не обязательно с использованием БД. В моем понимании я одно и то же говорю, видимо, не так доходчиво как хотелось бы, если еще не понятно задай плс более подробные уточняющие вопросы.

2017-05-14 16:49 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/NotificationResults.java
> +    public static List<Notification> getShortQueryErrorResult() {
Мне не нравится такое решение с созданием искусственного Suggest. Перегон в отдельный класс и использование конвертера кажется костылем, если можно генерить их напрямую, нотификации это все же не подсказки. Есть идея сделать кастомные ошибки для таких нотификаций и отлавливать их выше.

2017-05-14 16:49 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/HandlersStorage.java
> +class HandlersStorage {
Это точно не Storage, storage - это сущность в которую можно что-то положить и что-то достать без лишней логики, а здесь Handler выбирается на основании ответа, во всяких http фреймворках это что-то типа dispatcher.

2017-05-14 16:53 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Хорошо, я удалю класс Handler, сделаю MessageHandler интерфейсом и для каждого хэндлеры напишу свой конструктор, и у почти каждого будут те же 2 поля. Так лучше будет?

2017-05-14 17:17 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Идея с одной базовой сущностью для обработчиков норм, только я бы Handler сделал интерфейсом. Вообще идея такая начальная точка у нас onUpdateReceived, оттуда берется update, перекидывается в метод dispatch Dispatcher, в котором выбирается Handler, и у handler затем дергается метод handle который как-то это обрабатывает (для suggest и message по своему, возможно, сделал бы абстрактные классы для них как раз реализующие Handler)

2017-05-14 17:24 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Проблема в том, что suggest и message возвращают разные сущности, а chosenSuggest вообще войд, и сделать один handle под них не получится.

2017-05-14 17:38 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/NotificationResults.java
> +    public static List<Notification> getShortQueryErrorResult() {
Вопрос, где их отлавливать. Тут идея в том, чтобы хэндлеры ничего не знали о телеграмме, на случай других мессенджеров и вообще так правильнее. А сам хэндлеры мы дергаем из ботБоди, прям в нем ловить? Ну в принципе как вариант можно

2017-05-14 18:11 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Можно было бы сделать через Generic. Хотя тут еще другая проблема, в одном случае нам надо дергать `bot.sendMessage`, в другом `bot.answerInlineQuery`, в третьем ничего, что показывает разную сущность handler и мешает получить профит от общего Handler. Нужно это еще обдумать.

2017-05-14 18:30 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/Handler.java
> +        // TODO not all handlers require DBService
Ну, например, мы бы сделали класс TelegramResponse, от него отнаследовали бы MessageTelegramResponse, InlineTelegramResponse и затем на основании типа внутренней enum определяли бы, как отправлять, а сигнатура была бы такая `TelegramResponse handle(Update update)`.

2017-05-14 18:33 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/suggest/NotificationResults.java
> +    public static List<Notification> getShortQueryErrorResult() {
Я думал, что наши хэндлеры привязаны к телеграму жестко, если нет то надо будет писать обертки, и обдумывать на что нам не хватит времени скорее всего. На уровне BotBody уже не то, это должен делать обработчик.

2017-05-14 19:58 UTC, khasanovbi approved these changes

2017-05-14 20:44 UTC, merged