61 new questions
hh-school/bot-resume-builder pull request #58
Opened 2017-05-15 12:25 UTC by savinsergey

Подготовлен рабочий опросник и методы сохранения для него.

2017-05-15 12:40 UTC, khasanovbi requested changes

2017-05-15 12:40 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/gender/Gender.java
> +        if (code == 'M' || code == 'm' || code == 'М' || code == 'м' || code == 'О') {
Давай вынесем русские символы отсюда, это уже не код пола для работы с БД, а конвертация.

2017-05-15 12:40 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> +    private Set<Industry> industries = new HashSet<>(0);
зачем нужна такая инициализация?

2017-05-15 13:06 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/gender/Gender.java
> +        if (code == 'M' || code == 'm' || code == 'М' || code == 'м' || code == 'О') {
И куда их вынести?

2017-05-15 13:06 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> +    private Set<Industry> industries = new HashSet<>(0);
Показалось, что без неё ошибки, сейчас уберу

2017-05-15 13:31 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/gender/Gender.java
> +        if (code == 'M' || code == 'm' || code == 'М' || code == 'м' || code == 'О') {
там где юзаешь, либо в какие-то утилиты, которые тоже будут с тем местом где используешь

2017-05-15 13:47 UTC, khasanovbi requested changes

2017-05-15 13:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    private Set<Specialization> specializations = new HashSet<>(0);
тут тоже HashSet, какая ошибка возникала расскажи, плс.

2017-05-15 13:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        return String.format("firstName=%s, \nlastName='%s', \nnbirthDate='%s', \nphone='%s', \narea='%s', " +
`toString` использовался для отладки, мне не очень нравится перенесение логики отображения сообщения сюда.

2017-05-15 13:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> -        return Objects.hash(id, user.getId(), company.getId(),
Зачем компанию убрал?

2017-05-15 13:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
Объясни плс, зачем это, в какой API это не JsonArray?

2017-05-15 13:51 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> -        return Objects.hash(id, user.getId(), company.getId(),
У нас возможна ситуация, когда Experience в базе уже есть, а компании нет, возникает NPE

2017-05-15 13:51 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
для факультетов возвращается сразу JsonArray, без items

2017-05-15 13:53 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
Тогда надо просто убрать конвертер списка факультетов, а не городить этот огород

2017-05-15 13:56 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    private Set<Specialization> specializations = new HashSet<>(0);
Было падение при сохранении Experience, я сначала подумал, что из-за того, что сет неинициализирован, потом понял, что из-за company.getId() в функции hashCode

2017-05-15 13:56 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        return String.format("firstName=%s, \nlastName='%s', \nnbirthDate='%s', \nphone='%s', \narea='%s', " +
вообще это временное решение, могу убрать, если мешает.

2017-05-15 13:59 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> -        return Objects.hash(id, user.getId(), company.getId(),
Давай не будем удалять поля, а будем проверять на null

2017-05-15 14:00 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
Всмысле написать отдельный Deserializer?

2017-05-15 14:02 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
Нет, из `http.HHHTTPServiceFactory` удалить строчки `.registerTypeAdapter(new TypeToken<List<Faculty>>() {}.getType(), new ItemsDeserializer<Faculty>())`

2017-05-15 14:03 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        return String.format("firstName=%s, \nlastName='%s', \nnbirthDate='%s', \nphone='%s', \narea='%s', " +
Не мешает, просто не нравится) Вообще почему бы это не перенести в cv-билдер?

2017-05-15 14:03 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    private Set<Specialization> specializations = new HashSet<>(0);
давай тогда дропать HashSet

2017-05-15 14:13 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/http/type/adapter/ItemsDeserializer.java
> +        if (json.isJsonArray()) {
Какая-то магия внутри. Ок, сейчас

2017-05-15 14:24 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> -        return Objects.hash(id, user.getId(), company.getId(),
Исправил

2017-05-16 08:21 UTC, khasanovbi requested changes

2017-05-16 08:21 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/message/AnswerMessageHandler.java
> +                dbService.saveGender(telegramId, getGenderFromCode(value.charAt(0)));
почему бы тут полностью текст не передавать?

2017-05-16 08:21 UTC, khasanovbi commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        return String.format("firstName=%s, \n" +
Может как в других местах сделаем без переводов на newline? Idea сама такое же генерит.

2017-05-16 08:21 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Experience.java
> +                        "endDate=%s, description='%s'}", id, user.getId(), companyInfo, position,
По хорошему надо и для юзера на всякий случай так сделать. Можно было бы тернарным оператором проверять

2017-05-16 08:27 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/DBService.java
> +        log.error("Не найден опыт работы у пользователя {} по id", telegramId, user.getNodeRelationId());
placeholder'а нет

2017-05-16 11:18 UTC, khasanovbi requested changes

2017-05-16 11:18 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/experience/Company.java
> -        return String.format("Company{id=%d, name='%s', hhId = '%s', area = '%d'}", id, name, hhId, area.getId());
Тут тоже давай area вернем с тернарным оператором.

2017-05-16 11:18 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/cv/builder/PlainTextCVBuilder.java
> +        return dbService.getUserInfo(telegramId).replaceAll(", ", ", \n");
Давай перенесем содержимое getUserInfo сюда, точнее будем просто getUser вызывать, и тут же toString, replace.

2017-05-16 12:39 UTC, khasanovbi approved these changes

2017-05-16 12:42 UTC, merged