Phone number keyboard
hh-school/bot-resume-builder pull request #59
Opened 2017-05-16 12:37 UTC by savinsergey

Добавлено поле требуемой клавиатуры для вопрос
Добавлена реализация клавиатуры для телефона

2017-05-16 12:50 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
А если больше, то просто не засетим, это норм поведение?

2017-05-16 12:53 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
В целом да, мы сюда в целом попадаем только когда пользователь выбирает свой номер телефона(не тот, с которого он в телеграмме), то есть попытка сохранить текст ответа "хочу ввести свой телефон"

2017-05-16 21:43 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Ну допустим вот приходит человек со стороны, думает надо бы телефон засетить, не смотря в класс, думает ну сеттер же, но у него не засетится, и будет голову ломать почему телефон не засетился.

2017-05-16 22:18 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Ну до этого при попытке засетить телефон длиннее 15 символов бросался не обрабатываемый нормально экспешн. Что предлагаешь, сетить обрезок? Убрать ограничение на длину? Писать в лог ошибку?

2017-05-17 03:31 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Логирование в любом хорошо, но оно может быть отключено. Тут вопрос хотим ли мы валидировать в этом месте каждый раз при сете, если хотим да, лучше бросать ошибку. Но у нас же есть валидаторы в нодах и это можно было бы там проверять. Ошибка все равно, конечно, прилетит от БД. В итоге думаю, что лучше это в валидаторе чекать.

2017-05-17 05:05 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Я сделал questionNode такой, что в одном случае от юзера приходит телефон, а в другом сообщение типа "хочу ввести другой номер". Писать отдельный валидатор, который при нахождении букв превращает текст в "-1"?

2017-05-17 15:51 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
И поэтому тут стоит такая проверка? O_o. Нельзя перед валидатором отлавливать сообщение и не вызывать валидатор в случае "хочу ввести другой номер"?

2017-05-17 16:16 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
У нас внезапно один хэндлер, который принимает ответ. Делать такую проверку перед валидатором для каждого вопроса ещё страннее, делать проверку, что текущий вопрос про телефон и скипать сохранение если ответ " хочу ввести другой номер" совсем безумно

2017-05-17 17:26 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Окей, как тебе вариант валидировать в ноде либо ответ < 15 символов, либо "хочу ввести другой номер", чтобы не делать наследование.

2017-05-17 18:57 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Давай с начала: валидатор говорит, валидный ли ответ получен на вопрос или потребовать ещё раз ответ на этот же вопрос. Поэтому валидатором эту проблему не решить

2017-05-17 19:18 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Я понял, этот костыль с 15 символами сделан для того, чтобы не сохранять этот текст в базу.

2017-05-17 19:40 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Ну, видимо, надо пересмотреть концепцию одна нода - один сейвер. Давай проверку на это сообщение перенесем все-таки в `AnswerMessageHandler` и оставим // FIXME с комментом, почему так сделано пока что, проблема все-таки начинается именно с этой точки. PS. это дичь в любом месте.

2017-05-17 19:47 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Хотя можно новый сейвер сделать, который будет выбирать поле на основании ответа.

2017-05-18 09:22 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
так как мы везде используем абстрактный сейвер, то придется менять у всех сейверов метод getDatabaseField. Делать это я не буду, лучше уж в хэндлере проверять

2017-05-18 09:24 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
По хорошему надо пересмотреть концепцию "много нод - один хэндлер"

2017-05-18 09:45 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Возможно, стоит изменить валидатор так, чтобы он выдавал не тру фолс, а TRUE, FALSE, TRUE_BUT_NO_NEED_TO_SAVE

2017-05-18 09:55 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 15) {
Валидатор точно не должен говорить сохранять или нет.

2017-05-18 12:01 UTC, khasanovbi requested changes

2017-05-18 12:01 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 20) {
Зачем обрезать телефон, это вообще необычное поведение для юзера/разработчика будет.

2017-05-18 12:01 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/telegram/handler/message/AnswerMessageHandler.java
> +        } else if (currentNodeId == 3) {
Для информации: цепляться к id в коде это плохо, это может забыться при переделке опросника. Но лучше способа вроде нет, цепляться к названию филда тоже не особо, так что пускай пока так.

2017-05-18 12:18 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 20) {
при попытке сохранить телефон длиннее сейчас будет необрабатываемый эксепшн.

2017-05-18 12:19 UTC, savinsergey commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 20) {
А с таким условием только запись в логе об ошибке. Если разработчик не читает логи, это его проблемы. Можно добавить в валидаторе проверку на максимальную длину, но это не отменяет необходимость проверки в сеттере.

2017-05-18 12:38 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +        if (phone.length() <= 20) {
Добавь в валидатор лучше, я на это и намекал. 

Обрезать - это плохая альтернатива, это нестандартное поведение.
1) если разработчик захочет валидировать, он может это сделать в том месте где хочет засеттить;
2) иногда разработчику и без валидаторов, понятно, что он правильную сущность отдает, и он не хочет валидировать;
3) можно обрабатывать ошибку БД;
4) если все-таки допускаем невалидные запросы, но не хотим в БД отправлять такие запросы, можно свой ValidationException рейзить, который так же надо обрабатывать. Если пойдем по этому пути тогда надо во всех местах так сделать, для однозначности.

2017-05-18 13:42 UTC, savinsergey commented
давайте мы уже смержим этот пр, 2 дня висит. Какой смысл делать маленькие пр тогда, если время аппрува не зависит от размера?

2017-05-18 13:48 UTC, KhasanovBI commented on src/main/java/ru/hh/resumebuilderbot/database/model/User.java
> +    @Column(name = "phone", length = 20)
Давай это вынесем в `public static final int PHONE_LENGTH = 20;` эту константу будем использовать в валидаторе и тут, и  го мерджить.

2017-05-18 14:12 UTC, merged